<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="definitions\BPMN20.cmof" />
    <None Remove="definitions\BPMN20.xsd" />
    <None Remove="definitions\BPMNDI.cmof" />
    <None Remove="definitions\BPMNDI.xsd" />
    <None Remove="definitions\Semantic.xsd" />
    <None Remove="diagrams\all_icons.bpmn" />
    <None Remove="diagrams\all_tasks.bpmn" />
    <None Remove="diagrams\MonthlyInvoicing-solution.bpmn" />
    <None Remove="diagrams\single_user_task.bpmn" />
    <None Remove="diagrams\subprocesses.bpmn" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="definitions\BPMN20.cmof" />
    <EmbeddedResource Include="definitions\BPMN20.xsd" />
    <EmbeddedResource Include="definitions\BPMNDI.cmof" />
    <EmbeddedResource Include="definitions\BPMNDI.xsd" />
    <EmbeddedResource Include="definitions\Semantic.xsd" />
    <EmbeddedResource Include="diagrams\all_icons.bpmn" />
    <EmbeddedResource Include="diagrams\all_tasks.bpmn" />
    <EmbeddedResource Include="diagrams\MonthlyInvoicing-solution.bpmn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="diagrams\single_user_task.bpmn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="diagrams\subprocesses.bpmn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

</Project>
