/// <summary>
/// This file was generated by Python utility - do NOT modify it directly.
/// </summary>
namespace BPMNModel.Model
{
    public static class PostProcessing
    {
        public static void Process(object item)
        {
            // If BoundaryEvent get attachedToRef use it like Activity, put THIS into its List boundaryEventRefs
            if (item is BoundaryEvent casted0 && casted0.AttachedToRef is not null) casted0.AttachedToRef.BoundaryEventRefs.Add(casted0);

            // If ConversationLink get sourceRef use it like InteractionNode, put THIS into its List outgoingConversationLinks
            if (item is ConversationLink casted1 && casted1.SourceRef is not null) casted1.SourceRef.OutgoingConversationLinks.Add(casted1);

            // If ConversationLink get targetRef use it like InteractionNode, put THIS into its List incomingConversationLinks
            if (item is ConversationLink casted2 && casted2.TargetRef is not null) casted2.TargetRef.IncomingConversationLinks.Add(casted2);

            // If FlowElement get categoryValueRef for all elements used like CategoryValue, put THIS into its List categorizedFlowElements
            if (item is FlowElement casted3) casted3.CategoryValueRef.ForEach(x => x.CategorizedFlowElements.Add(casted3));

            // If InputSet get dataInputRefs for all elements used like DataInput, put THIS into its List inputSetRefs
            if (item is InputSet casted4) casted4.DataInputRefs.ForEach(x => x.InputSetRefs.Add(casted4));

            // If InputSet get optionalInputRefs for all elements used like DataInput, put THIS into its List inputSetWithOptional
            if (item is InputSet casted5) casted5.OptionalInputRefs.ForEach(x => x.InputSetWithOptional.Add(casted5));

            // If InputSet get whileExecutingInputRefs for all elements used like DataInput, put THIS into its List inputSetWithWhileExecuting
            if (item is InputSet casted6) casted6.WhileExecutingInputRefs.ForEach(x => x.InputSetWithWhileExecuting.Add(casted6));

            // If Lane get flowNodeRefs for all elements used like FlowNode, put THIS into its List lanes
            if (item is Lane casted7) casted7.FlowNodeRefs.ForEach(x => x.Lanes.Add(casted7));

            // If OutputSet get dataOutputRefs for all elements used like DataOutput, put THIS into its List outputSetRefs
            if (item is OutputSet casted8) casted8.DataOutputRefs.ForEach(x => x.OutputSetRefs.Add(casted8));

            // If OutputSet get optionalOutputRefs for all elements used like DataOutput, put THIS into its List outputSetWithOptional
            if (item is OutputSet casted9) casted9.OptionalOutputRefs.ForEach(x => x.OutputSetWithOptional.Add(casted9));

            // If OutputSet get whileExecutingOutputRefs for all elements used like DataOutput, put THIS into its List outputSetWithWhileExecuting
            if (item is OutputSet casted10) casted10.WhileExecutingOutputRefs.ForEach(x => x.OutputSetWithWhileExecuting.Add(casted10));

        }
    }
}
